let themesTxt = "Animés-/Animés-/Animés-/Animés-/Animés-/Animés-/Gaming-/Gaming-/Gaming-/Gaming-/Gaming-/Gaming-/Gaming-/Gaming-/Gaming-/Gaming-/Cinéma-/Cinéma-/Cinéma-/Cinéma-/Cinéma-/Cinéma-/Cinéma-/Cinéma-/Cinéma-/Cinéma-/Technologie-/Technologie-/Technologie-/Technologie-/Technologie-/Technologie-/Technologie-/Technologie-/Technologie-/Technologie"
    let q1Txt = "Où est-ce que Kaneki décide de travailler ?-/Comment s’appelle l’auteur que Kaneki aime beaucoup ?-/Dans quel manga ou anime, le héros est un petit robot ?-/Qui est l’étudiant  qui dépasse certain héro pro ?-/Qui emmène Eren au tribunal ?-/Lors du combat final contre Buu buu , Vegeta déclare que ?-/Quelle est l'année de sortie de la Super Nintendo en France ? -/Dans quelle ville est né Altaïr, le héros du premier Assassin's Creed ?-/Comment s’appel le puissant héro de God of war ?-/De quels jeux Franklin Michael Trevor sont-ils  issus ?-/Quel studio a développé Call of Duty: Advanced Warfare ?-/Quel est le nom du créateur de Mario ?-/Quel moteur graphique utilisé dans les jeux battlefield ?-/Dans the last of us comment appelle t’on le champignon responsable de l’infection ?-/Dans Apex Legend comment se nomme le héros possédant un corbeau ?-/Quel est le studio qui a crée la licence Assassin’s Creed ?-/De quel film est issu la musique culte « Now we are free »?-/Dans le film « La Chute du Faucon noir » quel est la force d’intervention à pied ?-/Dans le film gladiator qui assassine Marc Aurèle ? -/En quel lieu Frodon se fait-il blesser par l'un des neuf cavaliers noirs ?-/A travers quel artefact possédé par Saroumane voit-on luire l'oeil de Sauron ?-/Dans intouchable, qu’elle est l’handicape de Phillipe ?-/Dans The Amazing Spiderman quel est la vraie identité d’électro ?-/Dans X men origins Wolwerine Logan se prend une explosion de quel type ?-/Comment s’ appel le méchant qui a copié la technologie Stark lors du grand prix à Monaco ?-/Dans Transformers comment appelle t’on l’élément pouvant réanimer un transformers ?-/Que veut dire High tech ?-/Que veut dire RAM ?-/Quel est le rôle d’un processeur ?-/Où se trouve le siège d’Intel Corporation ?-/Que veut dire CPL ?-/Quel est le le classement juste  des stockages les plus rapides ?-/Quel type de connexion est la plus rapide ?-/Quel débit est le plus rapide ?-/Quel est le nouveau nom de Facebook?-/Qui est le successeur de Steve Jobs ?"
    let q2Txt = "Dans un bar.-/Takatsuki Sen-/Yume Senshi-/Lemillion-/Erwin Smith-/Goku est un imbécile-/1990-/Jérusalemen-/Credos-/Red dead rédemption 2-/Treyarch studio-/Akira Toriyama-/Unity-/Cordyceps-/Wraith-/Valve-/Gladiator-/Mac V SOG-/Spartacus-/Amon sûl-/Le miroir Galadriel-/Il est paraplégique-/Arthur Parks-/Incident industrielle-/Enton Vanko-/La Matrice de commandement-/Technologie-/Random Access Memory-/D’exécuter des fréquences d’images-/Santa Monica-/Courant porteur de liens-/HDD<SSD<SD<Flash Memory-/VDSL2-/Tera bits/s-/Méta-/Ragnar Lothbrok"
    let q3Txt= "Dans un café appelé l’Antique.-/Tachibana Sen-/Wingman-/Endevor-/Levy-/Goku est le numéro 1-/1991-/Rome-/Démios-/The last of us-/Sledge Hammer Games-/Shigeru Miyamoto-/Unreal Engine-/Coprin-/Sombra-/Bethesda-/Star Wars-/Les Marines-/Octave-/Le mont Ventoux-/Le bâton de pouvoir-/Il est tétraplégique-/Steeve Rogers-/Une explosion-/Ivan Vanko-/Le All Spark-/La petite technologie-/Right Acces Mobile-/D’échanger des données entre les différents composants informatique-/Santa Clara-/Couverture pérméable de ligne-/Flash Memory <SD< HDD<SSD-/Modem-/Gigabyte /s-/Messenger-/Mark Zuckerberg"
    let q4Txt= "Dans un restaurant pour Goule. -/Takatsuki Seido-/Astro Boy-/Hawks-/Hanzi Zoé-/Goku est le plus gentil des sayans-/1992-/Masyaf-/Kratos-/Grand Theft Auto 5-/Rockstar Games-/Zang Yamoto-/Rage-/Amanite Phalloïde-/Bloodhound-/Criterion-/Le seigneur des Anneaux-/La Delta Force-/Comode-/Le Gué de Bruinen-/Le Palantir-/Il est hémiplégique-/Max Dillon-/Une Explosion atomique-/Jin Khanè-/Le cube de commandement-/La haute technologie-/Rainbow Acces Memory-/De stocker des données-/Santa Barbara-/Courant porteur en ligne-/SD<SSD<Flash Memory<HDD-/ADSL-/Mégabyte/s-/Discord-/Richard Branson"
    let q5Txt = "À l’université.-/Akira Mado-/Gundam Wing-/Stain-/Mikasa Ackerman-/Goku est son plus grand rival-/1993-/Sparte-/Sakrot-/Grand theft Auto 4-/Infinity Ward-/Dashan Wang-/Frostbite-/Lactarius Amirus-/Mirage-/Ubisoft-/Il faut sauver le soldat Rayan-/Les Spetsnaz-/Maximus-/Le mont Valérien-/Le Tesseract-/Il est polyphylétique-/Curtis Connors-/Un tir de mortier-/Raymon Barkov-/Le tesseract commandement-/La techno-/Random Admin Memory-/De centraliser la prise en charge de la RAM-/Santa Clause-/Courant paramétrable de ligne-/SSD<HDD<Flash Memory<SD-/Fibre-/Microbytes /s-/Zétaverse-/Tim Cook"
    let repTxt= "2-/1-/3-/4-/2-/2-/2-/3-/3-/3-/2-/2-/4-/1-/3-/4-/1-/3-/3-/1-/3-/2-/3-/3-/2-/1-/3-/1-/2-/2-/3-/2-/4-/1-/1-/4"
    let scoreStat =[{pseudo:"",date:"",themes: "" , 
    q1:"",r1:"",repQ1:"",score1:0,
    q2:"",r2:"",repQ2:"",score2:0,
    q3:"",r3:"",repQ3:"",score3:0,
    q4:"",r4:"",repQ4:"",score4:0}]
let scoreStatTmp =[{pseudo:"admin",date:"",themes: "" , 
        q1:"",r1:"",repQ1:"",score1:0,
        q2:"",r2:"",repQ2:"",score2:0,
        q3:"",r3:"",repQ3:"",score3:0,
        q4:"",r4:"",repQ4:"",score4:0}]